# Generated by Django 2.1.3 on 2018-12-20 07:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=500)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sellingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('productImg', models.ImageField(blank=True, null=True, upload_to='D:\\MY\\My Projects\\software projects\\shadesProductUploader\\src\\shadesProductUploader\\media')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productType', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ProductTypes',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipmentNumber', models.CharField(max_length=50)),
                ('shipmentDate', models.DateField()),
                ('isClosed', models.BooleanField(default='False')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSection.Products')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSection.Shipment')),
            ],
            options={
                'verbose_name_plural': 'ShipmentDetails',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSection.ProductTypes'),
        ),
    ]
