# Generated by Django 2.1.3 on 2019-01-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='userCreated',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='userModified',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='userCreated',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='userModified',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentdetail',
            name='userCreated',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentdetail',
            name='userModified',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
