# Generated by Django 2.1.3 on 2019-04-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolour',
            name='colourImg',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
