# Generated by Django 2.1.3 on 2019-01-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
