# Generated by Django 2.1.3 on 2018-12-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentdetail',
            old_name='indprice',
            new_name='indPrice',
        ),
        migrations.AddField(
            model_name='shipmentdetail',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
