# Generated by Django 2.1.3 on 2018-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0002_auto_20181220_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
