# Generated by Django 2.1.3 on 2019-04-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0002_productcolour_colourimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducBrands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productBrand', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ProductBrand',
            },
        ),
    ]
