# Generated by Django 2.1.3 on 2019-01-02 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0002_shipment_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentCostFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemCost', models.CharField(max_length=500)),
                ('itemCostPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exchangeRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'CostFactors',
            },
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='cost',
            new_name='costBase',
        ),
        migrations.AddField(
            model_name='shipmentcostfactor',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSection.Shipment'),
        ),
    ]
