# Generated by Django 2.1.3 on 2018-12-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0004_auto_20181226_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='archived',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='shipmentdetail',
            name='archived',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productImg',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='D:\\MY\\My Projects\\software projects\\shadesProductUploader\\src\\shadesProductUploader\\media/%Y/%m/%d/'),
        ),
    ]
