# Generated by Django 2.1.3 on 2019-01-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0005_auto_20190102_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentcostfactor',
            name='costType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSection.CostType'),
        ),
    ]
