# Generated by Django 2.1.3 on 2018-12-27 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0005_auto_20181227_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdetail',
            name='billDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shipmentdetail',
            name='billNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
