# Generated by Django 2.1.3 on 2018-12-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0006_auto_20181227_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='isFinalized',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='billNumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
