# Generated by Django 2.1.3 on 2019-01-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0006_auto_20190102_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentcostfactor',
            name='costType',
        ),
        migrations.RemoveField(
            model_name='shipmentcostfactor',
            name='shipment',
        ),
        migrations.AddField(
            model_name='shipment',
            name='costFile',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to='D:\\MY\\My Projects\\software projects\\shadesProductUploader\\src\\shadesProductUploader\\media/Costing/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='costType',
        ),
        migrations.DeleteModel(
            name='ShipmentCostFactor',
        ),
    ]
