# Generated by Django 2.1.3 on 2019-01-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0007_auto_20190104_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='isCostbaseFinalized',
            field=models.BooleanField(default='False'),
        ),
    ]
